//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWF_Device
    {
        public int ID { get; set; }
        public string Dev_IMEI { get; set; }
        public string Dev_Type { get; set; }
        public string Dev_Man { get; set; }
    }
}
