//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWF_User
    {
        public GWF_User()
        {
            this.GWF_FriendRelation = new HashSet<GWF_FriendRelation>();
            this.GWF_Group = new HashSet<GWF_Group>();
            this.GWF_Profile = new HashSet<GWF_Profile>();
            this.GWF_User_Feed = new HashSet<GWF_User_Feed>();
            this.GWF_User_Group = new HashSet<GWF_User_Group>();
            this.GWF_geo_Location = new HashSet<GWF_geo_Location>();
        }
    
        public int ID { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_passwordMD5 { get; set; }
    
        public virtual HashSet<GWF_FriendRelation> GWF_FriendRelation { get; set; }
        public virtual HashSet<GWF_Group> GWF_Group { get; set; }
        public virtual HashSet<GWF_Profile> GWF_Profile { get; set; }
        public virtual HashSet<GWF_User_Feed> GWF_User_Feed { get; set; }
        public virtual HashSet<GWF_User_Group> GWF_User_Group { get; set; }
        public virtual HashSet<GWF_geo_Location> GWF_geo_Location { get; set; }
    }
}
