//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWF_geo_Location
    {
        public int ID { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
<<<<<<< HEAD
        public string user_id { get; set; }
        public System.DateTime timestamp { get; set; }
=======
>>>>>>> 40b8671987faa250f97d648567786278098522dc
    }
}
