//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WebServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GWF_DBContext : DbContext
    {
        public GWF_DBContext()
            : base("name=GPSWithFriends_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GWF_Device> GWF_Device { get; set; }
        public DbSet<GWF_Profile> GWF_Profile { get; set; }
        public DbSet<GWF_User> GWF_User { get; set; }
    }
}
