//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WCF_WebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWF_User_Group
    {
        public GWF_User_Group()
        {
            this.GWF_Group = new HashSet<GWF_Group>();
        }
    
        public int ID { get; set; }
        public string user_id { get; set; }
        public string group_id { get; set; }
        public string group_name { get; set; }
    
        public virtual HashSet<GWF_Group> GWF_Group { get; set; }
        public virtual GWF_User GWF_User { get; set; }
    }
}
