//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWF_WCF_WebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWF_User_Feed
    {
        public GWF_User_Feed()
        {
            this.GWF_Message = new HashSet<GWF_Message>();
        }
    
        public int ID { get; set; }
        public string user_id { get; set; }
        public string feed_id { get; set; }
    
        public virtual HashSet<GWF_Message> GWF_Message { get; set; }
        public virtual GWF_User GWF_User { get; set; }
    }
}
