//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace GPSWithFriends.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.UserActionSoap")]
    public interface UserActionSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.IAsyncResult BeginLogIn(GPSWithFriends.Server.LogInRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.LogInResponse EndLogIn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FastSignUp", ReplyAction="*")]
        System.IAsyncResult BeginFastSignUp(GPSWithFriends.Server.FastSignUpRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.FastSignUpResponse EndFastSignUp(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LogOut", ReplyAction="*")]
        System.IAsyncResult BeginLogOut(GPSWithFriends.Server.LogOutRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.LogOutResponse EndLogOut(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Follow", ReplyAction="*")]
        System.IAsyncResult BeginFollow(GPSWithFriends.Server.FollowRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.FollowResponse EndFollow(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UnFollow", ReplyAction="*")]
        System.IAsyncResult BeginUnFollow(GPSWithFriends.Server.UnFollowRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.UnFollowResponse EndUnFollow(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(GPSWithFriends.Server.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(GPSWithFriends.Server.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(string LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FastSignUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FastSignUp", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.FastSignUpRequestBody Body;
        
        public FastSignUpRequest() {
        }
        
        public FastSignUpRequest(GPSWithFriends.Server.FastSignUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FastSignUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nickName;
        
        public FastSignUpRequestBody() {
        }
        
        public FastSignUpRequestBody(string email, string password, string nickName) {
            this.email = email;
            this.password = password;
            this.nickName = nickName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FastSignUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FastSignUpResponse", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.FastSignUpResponseBody Body;
        
        public FastSignUpResponse() {
        }
        
        public FastSignUpResponse(GPSWithFriends.Server.FastSignUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FastSignUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FastSignUpResult;
        
        public FastSignUpResponseBody() {
        }
        
        public FastSignUpResponseBody(string FastSignUpResult) {
            this.FastSignUpResult = FastSignUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOut", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.LogOutRequestBody Body;
        
        public LogOutRequest() {
        }
        
        public LogOutRequest(GPSWithFriends.Server.LogOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uid;
        
        public LogOutRequestBody() {
        }
        
        public LogOutRequestBody(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.LogOutResponseBody Body;
        
        public LogOutResponse() {
        }
        
        public LogOutResponse(GPSWithFriends.Server.LogOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogOutResult;
        
        public LogOutResponseBody() {
        }
        
        public LogOutResponseBody(string LogOutResult) {
            this.LogOutResult = LogOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FollowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Follow", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.FollowRequestBody Body;
        
        public FollowRequest() {
        }
        
        public FollowRequest(GPSWithFriends.Server.FollowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FollowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uid;
        
        public FollowRequestBody() {
        }
        
        public FollowRequestBody(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FollowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FollowResponse", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.FollowResponseBody Body;
        
        public FollowResponse() {
        }
        
        public FollowResponse(GPSWithFriends.Server.FollowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FollowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FollowResult;
        
        public FollowResponseBody() {
        }
        
        public FollowResponseBody(string FollowResult) {
            this.FollowResult = FollowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnFollowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnFollow", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.UnFollowRequestBody Body;
        
        public UnFollowRequest() {
        }
        
        public UnFollowRequest(GPSWithFriends.Server.UnFollowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnFollowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uid;
        
        public UnFollowRequestBody() {
        }
        
        public UnFollowRequestBody(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnFollowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnFollowResponse", Namespace="http://tempuri.org/", Order=0)]
        public GPSWithFriends.Server.UnFollowResponseBody Body;
        
        public UnFollowResponse() {
        }
        
        public UnFollowResponse(GPSWithFriends.Server.UnFollowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnFollowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnFollowResult;
        
        public UnFollowResponseBody() {
        }
        
        public UnFollowResponseBody(string UnFollowResult) {
            this.UnFollowResult = UnFollowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserActionSoapChannel : GPSWithFriends.Server.UserActionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastSignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FastSignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FollowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FollowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnFollowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnFollowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserActionSoapClient : System.ServiceModel.ClientBase<GPSWithFriends.Server.UserActionSoap>, GPSWithFriends.Server.UserActionSoap {
        
        private BeginOperationDelegate onBeginLogInDelegate;
        
        private EndOperationDelegate onEndLogInDelegate;
        
        private System.Threading.SendOrPostCallback onLogInCompletedDelegate;
        
        private BeginOperationDelegate onBeginFastSignUpDelegate;
        
        private EndOperationDelegate onEndFastSignUpDelegate;
        
        private System.Threading.SendOrPostCallback onFastSignUpCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogOutDelegate;
        
        private EndOperationDelegate onEndLogOutDelegate;
        
        private System.Threading.SendOrPostCallback onLogOutCompletedDelegate;
        
        private BeginOperationDelegate onBeginFollowDelegate;
        
        private EndOperationDelegate onEndFollowDelegate;
        
        private System.Threading.SendOrPostCallback onFollowCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnFollowDelegate;
        
        private EndOperationDelegate onEndUnFollowDelegate;
        
        private System.Threading.SendOrPostCallback onUnFollowCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UserActionSoapClient() {
        }
        
        public UserActionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserActionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserActionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserActionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LogInCompletedEventArgs> LogInCompleted;
        
        public event System.EventHandler<FastSignUpCompletedEventArgs> FastSignUpCompleted;
        
        public event System.EventHandler<LogOutCompletedEventArgs> LogOutCompleted;
        
        public event System.EventHandler<FollowCompletedEventArgs> FollowCompleted;
        
        public event System.EventHandler<UnFollowCompletedEventArgs> UnFollowCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.UserActionSoap.BeginLogIn(GPSWithFriends.Server.LogInRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogIn(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogIn(string email, string password, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.LogInRequest inValue = new GPSWithFriends.Server.LogInRequest();
            inValue.Body = new GPSWithFriends.Server.LogInRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((GPSWithFriends.Server.UserActionSoap)(this)).BeginLogIn(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.LogInResponse GPSWithFriends.Server.UserActionSoap.EndLogIn(System.IAsyncResult result) {
            return base.Channel.EndLogIn(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndLogIn(System.IAsyncResult result) {
            GPSWithFriends.Server.LogInResponse retVal = ((GPSWithFriends.Server.UserActionSoap)(this)).EndLogIn(result);
            return retVal.Body.LogInResult;
        }
        
        private System.IAsyncResult OnBeginLogIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginLogIn(email, password, callback, asyncState);
        }
        
        private object[] OnEndLogIn(System.IAsyncResult result) {
            string retVal = this.EndLogIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogInCompleted(object state) {
            if ((this.LogInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogInCompleted(this, new LogInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogInAsync(string email, string password) {
            this.LogInAsync(email, password, null);
        }
        
        public void LogInAsync(string email, string password, object userState) {
            if ((this.onBeginLogInDelegate == null)) {
                this.onBeginLogInDelegate = new BeginOperationDelegate(this.OnBeginLogIn);
            }
            if ((this.onEndLogInDelegate == null)) {
                this.onEndLogInDelegate = new EndOperationDelegate(this.OnEndLogIn);
            }
            if ((this.onLogInCompletedDelegate == null)) {
                this.onLogInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogInCompleted);
            }
            base.InvokeAsync(this.onBeginLogInDelegate, new object[] {
                        email,
                        password}, this.onEndLogInDelegate, this.onLogInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.UserActionSoap.BeginFastSignUp(GPSWithFriends.Server.FastSignUpRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFastSignUp(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginFastSignUp(string email, string password, string nickName, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.FastSignUpRequest inValue = new GPSWithFriends.Server.FastSignUpRequest();
            inValue.Body = new GPSWithFriends.Server.FastSignUpRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.nickName = nickName;
            return ((GPSWithFriends.Server.UserActionSoap)(this)).BeginFastSignUp(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.FastSignUpResponse GPSWithFriends.Server.UserActionSoap.EndFastSignUp(System.IAsyncResult result) {
            return base.Channel.EndFastSignUp(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndFastSignUp(System.IAsyncResult result) {
            GPSWithFriends.Server.FastSignUpResponse retVal = ((GPSWithFriends.Server.UserActionSoap)(this)).EndFastSignUp(result);
            return retVal.Body.FastSignUpResult;
        }
        
        private System.IAsyncResult OnBeginFastSignUp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string nickName = ((string)(inValues[2]));
            return this.BeginFastSignUp(email, password, nickName, callback, asyncState);
        }
        
        private object[] OnEndFastSignUp(System.IAsyncResult result) {
            string retVal = this.EndFastSignUp(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFastSignUpCompleted(object state) {
            if ((this.FastSignUpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FastSignUpCompleted(this, new FastSignUpCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FastSignUpAsync(string email, string password, string nickName) {
            this.FastSignUpAsync(email, password, nickName, null);
        }
        
        public void FastSignUpAsync(string email, string password, string nickName, object userState) {
            if ((this.onBeginFastSignUpDelegate == null)) {
                this.onBeginFastSignUpDelegate = new BeginOperationDelegate(this.OnBeginFastSignUp);
            }
            if ((this.onEndFastSignUpDelegate == null)) {
                this.onEndFastSignUpDelegate = new EndOperationDelegate(this.OnEndFastSignUp);
            }
            if ((this.onFastSignUpCompletedDelegate == null)) {
                this.onFastSignUpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFastSignUpCompleted);
            }
            base.InvokeAsync(this.onBeginFastSignUpDelegate, new object[] {
                        email,
                        password,
                        nickName}, this.onEndFastSignUpDelegate, this.onFastSignUpCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.UserActionSoap.BeginLogOut(GPSWithFriends.Server.LogOutRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogOut(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogOut(string uid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.LogOutRequest inValue = new GPSWithFriends.Server.LogOutRequest();
            inValue.Body = new GPSWithFriends.Server.LogOutRequestBody();
            inValue.Body.uid = uid;
            return ((GPSWithFriends.Server.UserActionSoap)(this)).BeginLogOut(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.LogOutResponse GPSWithFriends.Server.UserActionSoap.EndLogOut(System.IAsyncResult result) {
            return base.Channel.EndLogOut(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndLogOut(System.IAsyncResult result) {
            GPSWithFriends.Server.LogOutResponse retVal = ((GPSWithFriends.Server.UserActionSoap)(this)).EndLogOut(result);
            return retVal.Body.LogOutResult;
        }
        
        private System.IAsyncResult OnBeginLogOut(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return this.BeginLogOut(uid, callback, asyncState);
        }
        
        private object[] OnEndLogOut(System.IAsyncResult result) {
            string retVal = this.EndLogOut(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogOutCompleted(object state) {
            if ((this.LogOutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogOutCompleted(this, new LogOutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogOutAsync(string uid) {
            this.LogOutAsync(uid, null);
        }
        
        public void LogOutAsync(string uid, object userState) {
            if ((this.onBeginLogOutDelegate == null)) {
                this.onBeginLogOutDelegate = new BeginOperationDelegate(this.OnBeginLogOut);
            }
            if ((this.onEndLogOutDelegate == null)) {
                this.onEndLogOutDelegate = new EndOperationDelegate(this.OnEndLogOut);
            }
            if ((this.onLogOutCompletedDelegate == null)) {
                this.onLogOutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogOutCompleted);
            }
            base.InvokeAsync(this.onBeginLogOutDelegate, new object[] {
                        uid}, this.onEndLogOutDelegate, this.onLogOutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.UserActionSoap.BeginFollow(GPSWithFriends.Server.FollowRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFollow(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginFollow(string uid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.FollowRequest inValue = new GPSWithFriends.Server.FollowRequest();
            inValue.Body = new GPSWithFriends.Server.FollowRequestBody();
            inValue.Body.uid = uid;
            return ((GPSWithFriends.Server.UserActionSoap)(this)).BeginFollow(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.FollowResponse GPSWithFriends.Server.UserActionSoap.EndFollow(System.IAsyncResult result) {
            return base.Channel.EndFollow(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndFollow(System.IAsyncResult result) {
            GPSWithFriends.Server.FollowResponse retVal = ((GPSWithFriends.Server.UserActionSoap)(this)).EndFollow(result);
            return retVal.Body.FollowResult;
        }
        
        private System.IAsyncResult OnBeginFollow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return this.BeginFollow(uid, callback, asyncState);
        }
        
        private object[] OnEndFollow(System.IAsyncResult result) {
            string retVal = this.EndFollow(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFollowCompleted(object state) {
            if ((this.FollowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FollowCompleted(this, new FollowCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FollowAsync(string uid) {
            this.FollowAsync(uid, null);
        }
        
        public void FollowAsync(string uid, object userState) {
            if ((this.onBeginFollowDelegate == null)) {
                this.onBeginFollowDelegate = new BeginOperationDelegate(this.OnBeginFollow);
            }
            if ((this.onEndFollowDelegate == null)) {
                this.onEndFollowDelegate = new EndOperationDelegate(this.OnEndFollow);
            }
            if ((this.onFollowCompletedDelegate == null)) {
                this.onFollowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFollowCompleted);
            }
            base.InvokeAsync(this.onBeginFollowDelegate, new object[] {
                        uid}, this.onEndFollowDelegate, this.onFollowCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.UserActionSoap.BeginUnFollow(GPSWithFriends.Server.UnFollowRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnFollow(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUnFollow(string uid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.UnFollowRequest inValue = new GPSWithFriends.Server.UnFollowRequest();
            inValue.Body = new GPSWithFriends.Server.UnFollowRequestBody();
            inValue.Body.uid = uid;
            return ((GPSWithFriends.Server.UserActionSoap)(this)).BeginUnFollow(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.UnFollowResponse GPSWithFriends.Server.UserActionSoap.EndUnFollow(System.IAsyncResult result) {
            return base.Channel.EndUnFollow(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUnFollow(System.IAsyncResult result) {
            GPSWithFriends.Server.UnFollowResponse retVal = ((GPSWithFriends.Server.UserActionSoap)(this)).EndUnFollow(result);
            return retVal.Body.UnFollowResult;
        }
        
        private System.IAsyncResult OnBeginUnFollow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return this.BeginUnFollow(uid, callback, asyncState);
        }
        
        private object[] OnEndUnFollow(System.IAsyncResult result) {
            string retVal = this.EndUnFollow(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnFollowCompleted(object state) {
            if ((this.UnFollowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnFollowCompleted(this, new UnFollowCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnFollowAsync(string uid) {
            this.UnFollowAsync(uid, null);
        }
        
        public void UnFollowAsync(string uid, object userState) {
            if ((this.onBeginUnFollowDelegate == null)) {
                this.onBeginUnFollowDelegate = new BeginOperationDelegate(this.OnBeginUnFollow);
            }
            if ((this.onEndUnFollowDelegate == null)) {
                this.onEndUnFollowDelegate = new EndOperationDelegate(this.OnEndUnFollow);
            }
            if ((this.onUnFollowCompletedDelegate == null)) {
                this.onUnFollowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnFollowCompleted);
            }
            base.InvokeAsync(this.onBeginUnFollowDelegate, new object[] {
                        uid}, this.onEndUnFollowDelegate, this.onUnFollowCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GPSWithFriends.Server.UserActionSoap CreateChannel() {
            return new UserActionSoapClientChannel(this);
        }
        
        private class UserActionSoapClientChannel : ChannelBase<GPSWithFriends.Server.UserActionSoap>, GPSWithFriends.Server.UserActionSoap {
            
            public UserActionSoapClientChannel(System.ServiceModel.ClientBase<GPSWithFriends.Server.UserActionSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogIn(GPSWithFriends.Server.LogInRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("LogIn", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.LogInResponse EndLogIn(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.LogInResponse _result = ((GPSWithFriends.Server.LogInResponse)(base.EndInvoke("LogIn", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFastSignUp(GPSWithFriends.Server.FastSignUpRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("FastSignUp", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.FastSignUpResponse EndFastSignUp(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.FastSignUpResponse _result = ((GPSWithFriends.Server.FastSignUpResponse)(base.EndInvoke("FastSignUp", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogOut(GPSWithFriends.Server.LogOutRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("LogOut", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.LogOutResponse EndLogOut(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.LogOutResponse _result = ((GPSWithFriends.Server.LogOutResponse)(base.EndInvoke("LogOut", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFollow(GPSWithFriends.Server.FollowRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Follow", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.FollowResponse EndFollow(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.FollowResponse _result = ((GPSWithFriends.Server.FollowResponse)(base.EndInvoke("Follow", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUnFollow(GPSWithFriends.Server.UnFollowRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UnFollow", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.UnFollowResponse EndUnFollow(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.UnFollowResponse _result = ((GPSWithFriends.Server.UnFollowResponse)(base.EndInvoke("UnFollow", _args, result)));
                return _result;
            }
        }
    }
}
